-- DE STAMPERTJES v2.13 - STABLE FOUNDATION MIGRATION
-- Veilig voor een bestaande database.
-- Verwijdert geen Café-berichten, highscores of statistieken.
--
-- Beheercode:
-- MijnStampertjes2026!

begin;

-- 1. ADMIN SETTINGS
create table if not exists public.stampertjes_admin_settings (
  id integer primary key default 1 check (id=1)
);

alter table public.stampertjes_admin_settings
  add column if not exists admin_code text;

update public.stampertjes_admin_settings
set admin_code='MijnStampertjes2026!'
where id=1;

insert into public.stampertjes_admin_settings(id,admin_code)
select 1,'MijnStampertjes2026!'
where not exists (
  select 1 from public.stampertjes_admin_settings where id=1
);

alter table public.stampertjes_admin_settings
  alter column admin_code set not null;

alter table public.stampertjes_admin_settings enable row level security;
revoke all on public.stampertjes_admin_settings from anon, authenticated;

-- 2. COMMUNITY POSTS
create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  name text not null default 'SPELER',
  type text not null default 'Algemeen',
  message text not null,
  likes integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.community_posts
  add column if not exists device_id uuid;

create index if not exists community_posts_created_idx
on public.community_posts(created_at desc);

create index if not exists community_posts_device_idx
on public.community_posts(device_id);

alter table public.community_posts enable row level security;

-- Publiek direct alleen lezen; mutaties via RPC.
revoke insert, update, delete on public.community_posts from anon, authenticated;
grant select on public.community_posts to anon, authenticated;

-- 3. ADMIN VERIFY
create or replace function public.verify_stampertjes_admin(
  p_admin_code text
)
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select coalesce(
    (
      select admin_code = coalesce(p_admin_code,'')
      from public.stampertjes_admin_settings
      where id=1
    ),
    false
  );
$$;

-- 4. PLAYER POSTS
create or replace function public.create_community_post(
  p_device_id uuid,
  p_player_name text,
  p_type text,
  p_message text
)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if p_device_id is null then
    raise exception 'device_id required';
  end if;

  if p_type not in ('Algemeen','Idee','Bug','Highscore') then
    raise exception 'invalid type';
  end if;

  if char_length(trim(coalesce(p_message,''))) < 2 then
    raise exception 'message too short';
  end if;

  insert into public.community_posts(name,type,message,likes,device_id)
  values (
    upper(left(coalesce(nullif(trim(p_player_name),''),'SPELER'),10)),
    p_type,
    left(trim(p_message),240),
    0,
    p_device_id
  );
end;
$$;

create or replace function public.update_own_community_post(
  p_post_id bigint,
  p_device_id uuid,
  p_player_name text,
  p_type text,
  p_message text
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  affected integer;
begin
  if p_type not in ('Algemeen','Idee','Bug','Highscore') then
    return false;
  end if;

  update public.community_posts
  set name=upper(left(coalesce(nullif(trim(p_player_name),''),'SPELER'),10)),
      type=p_type,
      message=left(trim(p_message),240)
  where id=p_post_id
    and device_id=p_device_id;

  get diagnostics affected=row_count;
  return affected=1;
end;
$$;

create or replace function public.delete_own_community_post(
  p_post_id bigint,
  p_device_id uuid
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  affected integer;
begin
  delete from public.community_posts
  where id=p_post_id
    and device_id=p_device_id;

  get diagnostics affected=row_count;
  return affected=1;
end;
$$;

create or replace function public.get_community_posts(
  p_device_id uuid
)
returns table(
  id bigint,
  name text,
  type text,
  message text,
  likes integer,
  created_at timestamptz,
  is_own boolean
)
language sql
stable
security definer
set search_path=public
as $$
  select
    p.id,
    p.name,
    p.type,
    p.message,
    p.likes,
    p.created_at,
    (p.device_id is not null and p.device_id=p_device_id) as is_own
  from public.community_posts p
  order by p.created_at desc
  limit 100;
$$;

create or replace function public.like_community_post(
  p_post_id bigint
)
returns void
language sql
security definer
set search_path=public
as $$
  update public.community_posts
  set likes=least(likes+1,999999)
  where id=p_post_id;
$$;

-- 5. ADMIN POSTS
create or replace function public.admin_get_community_posts(
  p_admin_code text
)
returns table(
  id bigint,
  name text,
  type text,
  message text,
  likes integer,
  created_at timestamptz
)
language sql
stable
security definer
set search_path=public
as $$
  select p.id,p.name,p.type,p.message,p.likes,p.created_at
  from public.community_posts p
  where public.verify_stampertjes_admin(p_admin_code)
  order by p.created_at desc
  limit 200;
$$;

create or replace function public.admin_delete_community_post(
  p_post_id bigint,
  p_admin_code text
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  affected integer;
begin
  if public.verify_stampertjes_admin(p_admin_code) is not true then
    return false;
  end if;

  delete from public.community_posts where id=p_post_id;
  get diagnostics affected=row_count;
  return affected=1;
end;
$$;

-- 6. RIGHTS
revoke all on function public.verify_stampertjes_admin(text) from public;
revoke all on function public.create_community_post(uuid,text,text,text) from public;
revoke all on function public.update_own_community_post(bigint,uuid,text,text,text) from public;
revoke all on function public.delete_own_community_post(bigint,uuid) from public;
revoke all on function public.get_community_posts(uuid) from public;
revoke all on function public.like_community_post(bigint) from public;
revoke all on function public.admin_get_community_posts(text) from public;
revoke all on function public.admin_delete_community_post(bigint,text) from public;

grant execute on function public.verify_stampertjes_admin(text) to anon, authenticated;
grant execute on function public.create_community_post(uuid,text,text,text) to anon, authenticated;
grant execute on function public.update_own_community_post(bigint,uuid,text,text,text) to anon, authenticated;
grant execute on function public.delete_own_community_post(bigint,uuid) to anon, authenticated;
grant execute on function public.get_community_posts(uuid) to anon, authenticated;
grant execute on function public.like_community_post(bigint) to anon, authenticated;
grant execute on function public.admin_get_community_posts(text) to anon, authenticated;
grant execute on function public.admin_delete_community_post(bigint,text) to anon, authenticated;

commit;

-- Controle: moet TRUE teruggeven.
select public.verify_stampertjes_admin('MijnStampertjes2026!') as admin_code_ok;
