-- De Stampertjes v2.22.5 — wallpaper downloadregistratie
begin;
create table if not exists public.wallpaper_downloads (id bigint generated by default as identity primary key,device_id uuid,wallpaper_key text not null,created_at timestamptz not null default now(),constraint wallpaper_downloads_key_check check (wallpaper_key in ('kasteel_nacht','entreehal','kasteel_banner','vera_bug_tester')));
create index if not exists wallpaper_downloads_key_created_idx on public.wallpaper_downloads(wallpaper_key,created_at desc);
alter table public.wallpaper_downloads enable row level security;
revoke all on public.wallpaper_downloads from anon, authenticated;
create or replace function public.register_wallpaper_download(p_device_id uuid,p_wallpaper_key text) returns void language plpgsql security definer set search_path=public as $$ begin if p_wallpaper_key not in ('kasteel_nacht','entreehal','kasteel_banner','vera_bug_tester') then return; end if; insert into public.wallpaper_downloads(device_id,wallpaper_key) values(p_device_id,p_wallpaper_key); end; $$;
revoke all on function public.register_wallpaper_download(uuid,text) from public;
grant execute on function public.register_wallpaper_download(uuid,text) to anon, authenticated;
create or replace function public.get_wallpaper_download_counts() returns jsonb language sql stable security definer set search_path=public as $$ select jsonb_build_object('kasteel_nacht',(select count(*) from public.wallpaper_downloads where wallpaper_key='kasteel_nacht'),'entreehal',(select count(*) from public.wallpaper_downloads where wallpaper_key='entreehal'),'kasteel_banner',(select count(*) from public.wallpaper_downloads where wallpaper_key='kasteel_banner'),'vera_bug_tester',(select count(*) from public.wallpaper_downloads where wallpaper_key='vera_bug_tester')); $$;
revoke all on function public.get_wallpaper_download_counts() from public;
grant execute on function public.get_wallpaper_download_counts() to anon, authenticated;
commit;
