-- De Stampertjes v2.22.6
-- Developer Portal: Top 20 highscorebeheer.
-- Geen zichtbare melding in de game; HANDMATIG is uitsluitend admin-metadata.

begin;

alter table public.highscores
  add column if not exists id bigint generated by default as identity;

alter table public.highscores
  add column if not exists is_manual boolean not null default false;

-- Bestaande rijen een ID geven indien de identity-kolom na migratie nog null bevat.
update public.highscores
set id = default
where id is null;

create unique index if not exists highscores_admin_id_uidx
  on public.highscores(id);

create or replace function public.admin_get_highscores(
  p_admin_code text
)
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
begin
  if public.verify_stampertjes_admin(p_admin_code) is not true then
    raise exception 'unauthorized';
  end if;

  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'id',id,
        'name',name,
        'score',score,
        'level',level,
        'created_at',created_at,
        'is_manual',is_manual
      )
      order by score desc, created_at asc, id asc
    )
    from (
      select id,name,score,level,created_at,is_manual
      from public.highscores
      order by score desc,created_at asc,id asc
      limit 20
    ) q
  ),'[]'::jsonb);
end;
$$;

create or replace function public.admin_add_highscore(
  p_admin_code text,
  p_name text,
  p_score integer,
  p_level integer default 1
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  new_id bigint;
begin
  if public.verify_stampertjes_admin(p_admin_code) is not true then
    raise exception 'unauthorized';
  end if;

  if coalesce(p_score,0) <= 0 then
    raise exception 'score must be greater than zero';
  end if;

  insert into public.highscores(name,score,level,is_manual)
  values(
    left(coalesce(nullif(trim(p_name),''),'SPELER'),30),
    p_score,
    greatest(coalesce(p_level,1),1),
    true
  )
  returning id into new_id;

  return new_id;
end;
$$;

create or replace function public.admin_update_highscore(
  p_admin_code text,
  p_id bigint,
  p_name text,
  p_score integer,
  p_level integer
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
  if public.verify_stampertjes_admin(p_admin_code) is not true then
    raise exception 'unauthorized';
  end if;

  update public.highscores
  set
    name=left(coalesce(nullif(trim(p_name),''),'SPELER'),30),
    score=greatest(coalesce(p_score,0),0),
    level=greatest(coalesce(p_level,1),1)
  where id=p_id;

  return found;
end;
$$;

create or replace function public.admin_delete_highscore(
  p_admin_code text,
  p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
  if public.verify_stampertjes_admin(p_admin_code) is not true then
    raise exception 'unauthorized';
  end if;

  delete from public.highscores
  where id=p_id;

  return found;
end;
$$;

revoke all on function public.admin_get_highscores(text) from public;
revoke all on function public.admin_add_highscore(text,text,integer,integer) from public;
revoke all on function public.admin_update_highscore(text,bigint,text,integer,integer) from public;
revoke all on function public.admin_delete_highscore(text,bigint) from public;

grant execute on function public.admin_get_highscores(text) to anon,authenticated;
grant execute on function public.admin_add_highscore(text,text,integer,integer) to anon,authenticated;
grant execute on function public.admin_update_highscore(text,bigint,text,integer,integer) to anon,authenticated;
grant execute on function public.admin_delete_highscore(text,bigint) to anon,authenticated;

commit;
