-- DE STAMPERTJES - STAMPERTJES CAFÉ
-- Eenmalig uitvoeren in Supabase: SQL Editor > New query > Run

create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 10),
  type text not null default 'Algemeen'
    check (type in ('Algemeen','Idee','Bug','Highscore','GJ Studios')),
  message text not null check (char_length(message) between 2 and 240),
  likes integer not null default 0 check (likes >= 0 and likes <= 999999),
  created_at timestamptz not null default now()
);

alter table public.community_posts enable row level security;

drop policy if exists "Iedereen mag cafeberichten lezen" on public.community_posts;
create policy "Iedereen mag cafeberichten lezen"
on public.community_posts
for select
to anon
using (true);

drop policy if exists "Iedereen mag cafeberichten plaatsen" on public.community_posts;
create policy "Iedereen mag cafeberichten plaatsen"
on public.community_posts
for insert
to anon
with check (
  char_length(name) between 1 and 10
  and type in ('Algemeen','Idee','Bug','Highscore','GJ Studios')
  and char_length(message) between 2 and 240
  and likes = 0
);

drop policy if exists "Iedereen mag likes aanpassen" on public.community_posts;
create policy "Iedereen mag likes aanpassen"
on public.community_posts
for update
to anon
using (true)
with check (
  char_length(name) between 1 and 10
  and type in ('Algemeen','Idee','Bug','Highscore','GJ Studios')
  and char_length(message) between 2 and 240
  and likes between 0 and 999999
);

grant select, insert, update on table public.community_posts to anon;
grant usage, select on sequence public.community_posts_id_seq to anon;

create index if not exists community_posts_created_idx
on public.community_posts (created_at desc);

create index if not exists community_posts_likes_idx
on public.community_posts (likes desc);
