const {test}=require('node:test');const a=require('node:assert/strict');const {boot}=require('./harness.cjs');
function fixture(t){const b=boot();t.after(()=>b.close());return b;}
test('HD beta boots with ten rooms and existing hall and wallpapers',t=>{const b=fixture(t);a.equal(b.w.document.querySelectorAll('.atlasRoom').length,10);a.ok(b.w.document.getElementById('hallSection'));a.equal(b.w.document.querySelectorAll('.wallpaperCard').length,4)});
test('all ten rooms retain their specific HD dimensions and geometry',t=>{const b=fixture(t);for(let i=1;i<=10;i++){b.evaluate(`state='intro';startingGame=false;startGame(${i})`);a.equal(b.evaluate('level'),i);a.equal(b.evaluate('devTestActive'),true);a.equal(b.evaluate('floors.length'),5);a.ok(b.evaluate('W>=480'));b.evaluate("draw()");}});
test('practice cannot change stats, consume reward or log gameplay',t=>{const b=fixture(t);b.w.localStorage.setItem('stampertjesPendingTeddyBonus','500');const stats=b.w.localStorage.getItem('stampertjesStats');b.evaluate('startGame(3);saveStats({bestScore:999});logGameEvent("death")');a.equal(b.w.localStorage.getItem('stampertjesStats'),stats);a.equal(b.w.localStorage.getItem('stampertjesPendingTeddyBonus'),'500');a.equal(b.evaluate('score'),0)});
test('boss encounter opens after level ten and continues at eleven',t=>{const b=fixture(t);b.evaluate('state="play";level=10;enemies=[];startFreeze=0;devTestActive=false;let done;CastleBoss.open=(practice,fn)=>{done=fn;};updateEnemies()');a.equal(b.evaluate('level'),11);a.equal(b.evaluate('state'),'boss');b.evaluate('done()');a.equal(b.evaluate('state'),'transition');b.runTimers(1900);a.equal(b.evaluate('state'),'play');a.equal(b.evaluate('level'),11)});
test('boss practice leaves normal records untouched and can exit',t=>{const b=fixture(t);const stats=b.w.localStorage.getItem('stampertjesStats');b.w.document.getElementById('bossPracticeBtn').click();a.equal(b.evaluate('state'),'boss');b.w.document.getElementById('bossQuit').click();a.equal(b.evaluate('state'),'intro');a.equal(b.w.localStorage.getItem('stampertjesStats'),stats)});
test('Escape pauses and resumes rather than quitting',t=>{const b=fixture(t);b.evaluate('startGame()');b.w.dispatchEvent(new b.w.KeyboardEvent('keydown',{key:'Escape'}));a.equal(b.evaluate('state'),'paused');b.runTimers(180);b.w.dispatchEvent(new b.w.KeyboardEvent('keydown',{key:'Escape'}));a.equal(b.evaluate('state'),'play')});
test('death resets flawless streak',t=>{const b=fixture(t);b.evaluate('startGame(2);player.invulnerable=0;flawlessLevels=2;playerKilledByEnemy()');a.equal(b.evaluate('levelDeaths'),1);a.equal(b.evaluate('flawlessLevels'),0)});
test('practice game over no longer throws or destroys menu',t=>{const b=fixture(t);b.evaluate('startGame(4);showGameOverPanel()');a.ok(b.w.document.getElementById('practiceEnd'));b.w.document.getElementById('devExitBtn').click();a.equal(b.evaluate('state'),'intro');a.ok(b.w.document.getElementById('bossPracticeBtn'))});
test('score names render as text',t=>{const b=fixture(t);b.evaluate('onlineScores=[{name:"<img src=x>",score:200,level:1}];renderHighscores()');a.equal(b.w.document.querySelectorAll('#scoreList img').length,0)});
test('blocked storage still allows boss and regular practice',()=>{const b=boot({blockedStorage:true});try{b.evaluate('startGame(1)');a.equal(b.evaluate('state'),'play');b.evaluate('openIntro()');b.w.document.getElementById('bossPracticeBtn').click();a.equal(b.evaluate('state'),'boss')}finally{b.close()}});

test('tap route in original game climbs then stops at destination',t=>{const b=fixture(t);b.evaluate('startGame(1);player.x=215;player.y=772;');for(let i=0;i<400;i++)b.evaluate('Object.assign(keys,CastleBossEngine.route(player,{x:300,floor:3},floors,ladders).keys);updatePlayer()');a.ok(Math.abs(b.evaluate('player.y')-597)<1);a.ok(Math.abs(b.evaluate('player.x')-300)<=5);});

test('death and new room cancel a pending tap route',t=>{const b=fixture(t);b.evaluate('startGame(1);let cancels=0;CastleTouch.cancel=()=>cancels++;showDeathSequence(false);spawnLevel();');a.equal(b.evaluate('cancels'),2);});
